# Generated by Django 4.2 on 2023-04-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion_categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id_ubigeo', models.BigAutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('num_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(verbose_name='date')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descuento_venta', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('telefono_proveedor', models.CharField(max_length=9)),
                ('pagina_web_proveedor', models.CharField(max_length=500)),
                ('ubigeo_proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.ubigeo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=11)),
                ('stock_producto', models.IntegerField(default=0)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cantidad', models.IntegerField(default=0)),
                ('monto_producto', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='ubigeo_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema_ventas.ubigeo'),
        ),
    ]
